// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhUUvpMZnQa3aATlE_M1qqGppsvoCSvs',
    appId: '1:1005097163732:web:545bef0aa86020d1e21441',
    messagingSenderId: '1005097163732',
    projectId: 'dummy-3985c',
    authDomain: 'dummy-3985c.firebaseapp.com',
    storageBucket: 'dummy-3985c.firebasestorage.app',
    measurementId: 'G-8SJMWM393Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr53BEafe2vcUYfXc9SYFMr9g3AL6UGBk',
    appId: '1:1005097163732:android:1439eca02d5ded9be21441',
    messagingSenderId: '1005097163732',
    projectId: 'dummy-3985c',
    storageBucket: 'dummy-3985c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0c0-hAHqLzBFjGwQEzaIdKhmr3HfrTA',
    appId: '1:1005097163732:ios:b5cc39948450fb51e21441',
    messagingSenderId: '1005097163732',
    projectId: 'dummy-3985c',
    storageBucket: 'dummy-3985c.firebasestorage.app',
    iosBundleId: 'com.example.flutterlearner',
  );
}
